# Generated by Django 3.2.6 on 2021-08-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='presentation',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='recording',
            field=models.URLField(blank=True, null=True),
        ),
    ]
